import { BgType } from 'types/typeBundle';

export const bgPaths: { [key: string]: BgType } = {
  롯데월드잠실점: 'AmusementPark',
  에버랜드: 'AmusementPark',
  롯데월드몰: 'Department',
  타임스퀘어: 'Department',
  '강남 MICE 관광특구': 'Department',
  '종로·청계 관광특구': 'Street',
  더현대서울: 'Department',
  '홍대 관광특구': 'Street',
  '명동 관광특구': 'Street',
  현대백화점무역센터점: 'Department',
  신세계백화점본점신관: 'Department',
  갤러리아백화점명품관WEST: 'Department',
  IFC몰: 'Department',
  롯데백화점본점: 'Department',
  현대백화점디큐브시티점: 'Department',
  현대백화점신촌점: 'Department',
  현대백화점압구정본점: 'Department',
  갤러리아백화점광교점: 'Department',
  신세계백화점강남점: 'Department',
  스타필드하남: 'Department',
  스타필드고양: 'Department',
  스타필드안성: 'Department',
  현대백화점판교점: 'Department',
  '경복궁·서촌마을': 'Palace',
  '창덕궁·종묘': 'Palace',
  강남역: 'Subway',
  고속터미널역: 'Subway',
  선릉역: 'Subway',
  신림역: 'Subway',
  역삼역: 'Subway',
  용산역: 'Subway',
  건대입구역: 'Subway',
  교대역: 'Subway',
  '신촌·이대역': 'Subway',
  왕십리역: 'Subway',
  'DMC(디지털미디어시티)': 'Subway',
  '이태원 관광특구': 'Street',
  가로수길: 'Street',
  성수카페거리: 'Street',
  '수유리 먹자골목': 'Street',
  '쌍문동 맛집거리': 'Street',
  압구정로데오거리: 'Street',
  '인사동·익선동': 'Street',
  '동대문 관광특구': 'Street',
  '낙산공원·이화마을': 'Park',
  북서울꿈의숲: 'Park',
  서울대공원: 'Park',
  어린이대공원: 'AmusementPark',
  서울숲공원: 'Park',
  월드컵공원: 'Park',
  '국립중앙박물관·용산가족공원': 'Park',
  뚝섬한강공원: 'HanRiver',
  망원한강공원: 'HanRiver',
  반포한강공원: 'HanRiver',
  이촌한강공원: 'HanRiver',
  잠실한강공원: 'HanRiver',
  '광화문·덕수궁': 'GwangHwa',
  북촌한옥마을: 'Tradition',
  남산공원: 'Namsan',
  잠실종합운동장: 'Park',
};
