import { BgType } from 'types/typeBundle';

export const bgPaths: Record<string, BgType> = {
  롯데월드잠실점: 'Christmas',
  에버랜드: 'Christmas',
  롯데월드몰: 'Department',
  타임스퀘어: 'Department',
  '강남 MICE 관광특구': 'Christmas',
  '종로·청계 관광특구': 'Christmas',
  '홍대 관광특구': 'Street',
  '명동 관광특구': 'Christmas',
  현대백화점무역센터점: 'Department',
  신세계백화점본점신관: 'Department',
  갤러리아백화점명품관WEST: 'Department',
  IFC몰: 'Department',
  롯데백화점본점: 'Department',
  현대백화점디큐브시티점: 'Department',
  현대백화점신촌점: 'Department',
  현대백화점압구정본점: 'Department',
  갤러리아백화점광교점: 'Department',
  신세계백화점강남점: 'Department',
  스타필드고양: 'Department',
  스타필드안성: 'Department',
  현대백화점판교점: 'Department',
  경복궁: 'Palace',
  '창덕궁·종묘': 'Palace',
  강남역: 'Christmas',
  고속터미널역: 'Subway',
  선릉역: 'Subway',
  신림역: 'Subway',
  역삼역: 'Subway',
  용산역: 'Subway',
  건대입구역: 'Christmas',
  교대역: 'Subway',
  '신촌·이대역': 'Christmas',
  왕십리역: 'Subway',
  'DMC(디지털미디어시티)': 'Subway',
  '이태원 관광특구': 'Christmas',
  가로수길: 'Christmas',
  성수카페거리: 'Christmas',
  '수유리 먹자골목': 'Street',
  '쌍문동 맛집거리': 'Street',
  압구정로데오거리: 'Christmas',
  '인사동·익선동': 'Christmas',
  '동대문 관광특구': 'Street',
  '낙산공원·이화마을': 'Park',
  북서울꿈의숲: 'Park',
  서울대공원: 'Park',
  어린이대공원: 'AmusementPark',
  서울숲공원: 'Christmas',
  '국립중앙박물관·용산가족공원': 'Park',
  뚝섬한강공원: 'HanRiver',
  망원한강공원: 'HanRiver',
  반포한강공원: 'HanRiver',
  이촌한강공원: 'HanRiver',
  잠실한강공원: 'HanRiver',
  '광화문·덕수궁': 'Christmas',
  북촌한옥마을: 'Tradition',
  남산공원: 'Christmas',
  잠실종합운동장: 'Park',
  '창동 신경제 중심지': 'Subway',
  '잠실 관광특구': 'Christmas',
  '영등포 타임스퀘어': 'Christmas',
  여의도: 'Christmas',
  서울역: 'Subway',
  신도림역: 'Subway',
  연신내역: 'Subway',
  가산디지털단지역: 'Subway',
  구로디지털단지역: 'Subway',
  혜화역: 'Christmas',
  '홍대입구역(2호선)': 'Christmas',
  여의도한강공원: 'HanRiver',
  양화한강공원: 'HanRiver',
  합정역: 'Christmas',
  노들섬: 'Park',
  잠원한강공원: 'HanRiver',
  난지한강공원: 'HanRiver',
  연남동: 'Christmas',
  서울광장: 'Christmas',
  삼각지역: 'Subway',
  청와대: 'BlueHouse',
  강서한강공원: 'HanRiver',
  '이태원 앤틱가구거리': 'Street',
  용리단길: 'Street',
  '덕수궁길·정동길': 'Street',
  광나루한강공원: 'HanRiver',
  '청담동 명품거리': 'Street',
  '신논현역·논현역': 'Subway',
  양재역: 'Subway',
  'DDP(동대문디자인플라자)': 'Christmas',
  이태원역: 'Subway',
  광화문광장: 'Christmas',
  동대문역: 'Subway',
  서촌: 'Tradition',
  뚝섬역: 'Subway',
  '해방촌·경리단길': 'Street',
  회기역: 'Subway',
  성신여대입구역: 'Subway',
  사당역: 'Subway',
  '서울식물원·마곡나루역': 'Subway',
  '방배역 먹자골목': 'Street',
  '덕수궁길•정동길': 'Street',
  '쌍문동 맛집 거리': 'Street',
  '4·19 카페거리': 'Street',
  천호역: 'Subway',
  '광장(전통)시장': 'Street',
  미아사거리역: 'Subway',
  노원역사거리: 'Street',
};
